/**
 * The section archive: shape, required parts, and who is allowed to write what.
 *
 * Three voices, kept physically apart — that is the whole point of the template:
 *
 *   一、原文线索   作者说的，每一句都要有逐字引文；每个小标题后跟一段 AI 视角
 *   二、共读推演   AI 推的，必须带依据 / 理由 / 限制 / 状态，且标注为非作者原意
 *   三、我的看法   读者说的，模型不许代笔（no `readerInput` ⇒ 必须是待填占位）
 *   四、留下的口子 作者没回答的 + 章末「在全书中的位置」
 *   五、状态与记忆 插件自己写（路径、覆盖度、state 是插件的事实，不是模型的）
 *
 * 机制与边界落在第二节，不落第一节：第一节只放作者明说的东西，把推出来的机制
 * 写进去就是替作者说话，那是这个插件最不能接受的一种失真。
 *
 * Section 五 is generated by the plugin on persist, not by the model. A model
 * asked to write down where a file lives will eventually write down a path that
 * does not exist, and an archive that misdescribes its own provenance is worse
 * than one that omits it.
 */

export const SECTION_NUMERALS = ['一', '二', '三', '四'];

export const REQUIRED_SECTIONS = [
  {
    numeral: '一',
    label: '原文线索',
    heading: '## 一、原文线索',
    rule: '每个小节的（作者主张 / 关键证据 / 作者洞见）都必须带至少一条 **逐字引文**；引文必须能在原文里逐字找到。每个小标题后面都要跟一段 `### AI 视角`。',
  },
  {
    numeral: '二',
    label: '共读推演',
    heading: '## 二、共读推演（AI 推断，非作者原意）',
    rule: '每条推演必须有 依据 / 理由 / 限制 / 状态 四项；依据要指向第一节的原文线索。',
  },
  {
    numeral: '三',
    label: '我的看法',
    heading: '## 三、我的看法（读者）',
    rule: '这一节属于读者。没有 readerInput 时必须原样写（待读者填写），不许代笔。',
  },
  {
    numeral: '四',
    label: '本节留下的口子',
    heading: '## 四、本节留下的口子',
    rule: '作者没回答的问题 / 文本没展开的线索 / 需要后续验证的假说；末尾还要有 `### 在全书中的位置`，讲这一章在论证链里承担什么功能。',
  },
];

/** The exact placeholder that stands in for the reader's own voice. */
export const READER_PLACEHOLDER = '（待读者填写）';

/** Per-subsection增量视角。作者没明说、但可以从原文推出来的东西。 */
export const AI_VIEW_HEADING = '### AI 视角';

/** 章末的定位段：这一章在全书论证链里承担什么功能。 */
export const BOOK_POSITION_HEADING = '### 在全书中的位置';

/**
 * 整章的 mental model，也是讲解的骨架。
 *
 * It sits before 一、原文线索 on purpose: the reader — and the next turn's
 * model — should meet the model before meeting the material. A lecture that
 * meets the material first comes out source-shaped no matter how good the
 * individual annotations are.
 */
export const CHAPTER_MODEL_HEADING = '## 这一章真正在解决什么';

/** 讲解顺序 + 为什么。原序与重排都要给理由。 */
export const TEACHING_ORDER_HEADING = '### 讲解顺序';

/**
 * The order block must say which of these it is. A reader is entitled to know
 * whether what they are hearing is the book's own order — and either answer
 * without a reason is indistinguishable from never having asked the question.
 */
export const ORDER_SHAPE_WORDS = ['原序', '原文顺序', '重排'];

/** What the AI view says when there is genuinely nothing incremental to add. */
export const NO_EXTRA_NOTE = '这一节我没有额外的补充';

/** Heading of the plugin-owned section. */
export const MEMORY_HEADING = '## 五、理解状态与记忆';

/** Section 二's heading must say out loud that it is inference, not the author. */
export const INFERENCE_MARKER = '推断';

/** Status vocabulary for an inference, from the blueprint. */
export const INFERENCE_STATES = ['待验证', '可接受', '存疑'];

/** Status vocabulary for the reader's understanding of the section. */
export const UNDERSTANDING_STATES = ['已懂', '困惑', '待验证'];

/**
 * The template handed to the model. Kept in one place so the prompt file and
 * the validator cannot drift apart.
 * @param {{ chapterId: string, title: string }} chapter
 */
export function renderTemplate(chapter) {
  const title = chapter.title === '' ? '（无标题）' : chapter.title;
  return [
    `# ${chapter.chapterId} ${title}`,
    '',
    '> 本节在全书中的位置：',
    '> （承接什么，开启什么，回答全书哪个核心问题）',
    '',
    CHAPTER_MODEL_HEADING,
    '',
    '{一段话：这一章的 mental model。不是章节摘要——摘要回答（讲了什么），这里回答（在解决什么）；长度以能当三句话读为限。}',
    '',
    TEACHING_ORDER_HEADING,
    '',
    '{选定的讲解顺序 + 理由。必须出现（原序）或（重排）之一：原序要说明为什么原序本身就在搭出上面这个模型；重排要说明原序哪里挡路。}',
    '',
    REQUIRED_SECTIONS[0].heading,
    '### {小标题}   ← 小标题的顺序 = 上面的讲解顺序，不必等于原书顺序',
    '- 作者主张：… **引文**',
    '- 关键证据／例子：… **引文**',
    '- 作者洞见：… **引文**',
    '',
    AI_VIEW_HEADING,
    `{一段，不超过 4 句。作者没明说但可以从原文推出来的机制 / 与全书的连接 / 一个反例。推不出就写（${NO_EXTRA_NOTE}）。}`,
    '',
    REQUIRED_SECTIONS[1].heading,
    '### 推演 1：{一句话结论}',
    '- 依据：…（指向第一节的哪条线索）',
    '- 理由：…',
    '- 限制：…',
    `- 状态：${INFERENCE_STATES.join(' / ')}`,
    '',
    REQUIRED_SECTIONS[2].heading,
    '### 我觉得最自洽的地方',
    READER_PLACEHOLDER,
    '### 我觉得滑太快／存疑的地方',
    READER_PLACEHOLDER,
    '### 我想继续追问的问题',
    READER_PLACEHOLDER,
    '',
    REQUIRED_SECTIONS[3].heading,
    '- {作者没回答的问题}',
    '- {文本没展开的线索}',
    '- {需要后续验证的假说}',
    '',
    BOOK_POSITION_HEADING,
    '{一段，这一章和前后章的关系，这一章在全书论证链里承担什么功能。}',
    '',
    `${MEMORY_HEADING}（这一节由插件在落盘时写入，你不要写）`,
  ].join('\n');
}

/**
 * The plugin-owned tail section. Every number in it comes from plugin state.
 * @param {{ chapterId: string, state: string, understanding: string, memoryPath: string,
 *           coveredChars: number, totalChars: number, nextStep: string,
 *           verification: string, revision: number }} facts
 */
export function renderMemorySection(facts) {
  return [
    MEMORY_HEADING,
    `- 理解状态：${facts.understanding}`,
    `- 档案 state：${facts.state}（覆盖 ${facts.coveredChars}/${facts.totalChars} 字）`,
    `- 校验：${facts.verification}`,
    `- 记忆：${facts.memoryPath}`,
    `- revision：${facts.revision}`,
    `- 下一步：${facts.nextStep}`,
  ].join('\n');
}

/**
 * Replace (or append) the plugin-owned section with authoritative facts.
 * @param {string} markdown
 * @param {string} section
 */
export function withMemorySection(markdown, section) {
  const lines = markdown.split('\n');
  const start = lines.findIndex((line) => line.trim().startsWith(MEMORY_HEADING));
  const body = start === -1 ? lines : lines.slice(0, start);
  while (body.length > 0 && body[body.length - 1].trim() === '') body.pop();
  return [...body, '', section, ''].join('\n');
}
